language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements-test.txt
script:
    - coverage run --source reference_sequence_fetcher -m py.test --cir
after_success:
  - coveralls
